<?php
/**
 * Configuration File generated by install.php
 * PT Data Lake Indonesia
 */

define('DB_TYPE', 'sqlite');
define('DB_HOST', '127.0.0.1');
define('DB_PORT', '3306');
define('DB_NAME', 'datalake_db');
define('DB_USER', 'shawir');
define('DB_PASS', 's131222');
define('INSTALLED_AT', '2026-10-03 21:14:12');
