<?php
/**
 * Configuration File generated by install.php
 * PT Data Lake Indonesia
 */

define('DB_TYPE', 'sqlite');
define('DB_HOST', '127.0.0.1');
define('DB_PORT', '3306');
define('DB_NAME', 'datalake_db');
define('DB_USER', 'root');
define('DB_PASS', '');
define('INSTALLED_AT', '2026-10-03 19:42:54');
