<?php
/**
 * Database Connection & Migration Handler
 * Supports both SQLite (Zero-config ready) and MySQL
 * PT Data Lake Indonesia Web Portal
 */

// Load custom configuration if generated by installer
if (file_exists(__DIR__ . '/config.php')) {
    require_once __DIR__ . '/config.php';
}

// Default Configuration Fallbacks (MySQL / phpMyAdmin by default)
if (!defined('DB_TYPE')) define('DB_TYPE', 'mysql'); // 'mysql' or 'sqlite'
if (!defined('DB_HOST')) define('DB_HOST', '127.0.0.1');
if (!defined('DB_PORT')) define('DB_PORT', '3306');
if (!defined('DB_NAME')) define('DB_NAME', 'datalake_db');
if (!defined('DB_USER')) define('DB_USER', 'root');
if (!defined('DB_PASS')) define('DB_PASS', '');

function get_db_connection() {
    static $pdo = null;

    if ($pdo !== null) {
        return $pdo;
    }

    try {
        if (DB_TYPE === 'sqlite') {
            $db_dir = __DIR__ . '/../database';
            if (!is_dir($db_dir)) {
                mkdir($db_dir, 0755, true);
            }
            $db_path = $db_dir . '/datalake.sqlite';
            $pdo = new PDO("sqlite:" . $db_path);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
            $pdo->exec("PRAGMA foreign_keys = ON;");
        } else {
            $dsn = "mysql:host=" . DB_HOST . ";port=" . DB_PORT . ";dbname=" . DB_NAME . ";charset=utf8mb4";
            $pdo = new PDO($dsn, DB_USER, DB_PASS, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ]);
        }

        // Initialize tables if needed
        init_db_tables($pdo);

    } catch (PDOException $e) {
        if (DB_TYPE === 'mysql') {
            die("
                <div style='font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif; max-width:640px; margin:60px auto; padding:28px; background:#fff; border-radius:14px; box-shadow:0 12px 35px rgba(0,0,0,0.1); border:1px solid #fee2e2;'>
                    <div style='display:flex; align-items:center; gap:12px; margin-bottom:16px;'>
                        <div style='width:40px; height:40px; border-radius:50%; background:#fef2f2; color:#dc2626; display:flex; align-items:center; justify-content:center; font-size:22px; font-weight:bold;'>!</div>
                        <h2 style='color:#b91c1c; margin:0; font-size:20px;'>Gagal Terhubung ke Database MySQL (phpMyAdmin)</h2>
                    </div>
                    <p style='color:#475569; font-size:14px; line-height:1.6;'>
                        Aplikasi dikonfigurasi untuk menggunakan <strong>MySQL (phpMyAdmin)</strong>, namun server belum berhasil tersambung dengan parameter berikut:
                    </p>
                    <div style='background:#f8fafc; border:1px solid #e2e8f0; border-radius:8px; padding:12px 16px; font-family:monospace; font-size:13px; color:#334155; margin-bottom:16px;'>
                        Host: <strong>" . htmlspecialchars(DB_HOST) . ":" . htmlspecialchars(DB_PORT) . "</strong><br>
                        Database: <strong>" . htmlspecialchars(DB_NAME) . "</strong><br>
                        User: <strong>" . htmlspecialchars(DB_USER) . "</strong>
                    </div>
                    <div style='background:#fff1f2; border:1px solid #fecdd3; border-radius:8px; padding:10px 14px; font-size:12.5px; color:#9f1239; margin-bottom:20px;'>
                        <strong>Pesan Error MySQL:</strong> " . htmlspecialchars($e->getMessage()) . "
                    </div>
                    <h4 style='color:#0f172a; margin:0 0 10px; font-size:14px;'>Cara Mengatasinya:</h4>
                    <ol style='color:#475569; font-size:13.5px; line-height:1.8; padding-left:20px; margin:0 0 20px;'>
                        <li>Buka <strong>phpMyAdmin</strong> di panel hosting/server Anda.</li>
                        <li>Pastikan database <code>" . htmlspecialchars(DB_NAME) . "</code> sudah dibuat (atau import file <code>database/schema.sql</code>).</li>
                        <li>Sesuaikan username & password database di file <code>config/config.php</code> atau jalankan Web Installer di bawah ini.</li>
                    </ol>
                    <div style='display:flex; gap:10px;'>
                        <a href='/install.php?force_unlock=1' style='background:#0284c7; color:#fff; text-decoration:none; padding:10px 18px; border-radius:8px; font-weight:600; font-size:13.5px; display:inline-block;'>
                            Buka Web Installer MySQL &rarr;
                        </a>
                        <a href='javascript:location.reload()' style='background:#f1f5f9; color:#334155; text-decoration:none; padding:10px 18px; border-radius:8px; font-weight:600; font-size:13.5px; display:inline-block;'>
                            Coba Ulang Koneksi
                        </a>
                    </div>
                </div>
            ");
        }
        die("Database Connection Error: " . htmlspecialchars($e->getMessage()));
    }

    return $pdo;
}

function init_db_tables(PDO $pdo) {
    $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

    if ($driver === 'sqlite') {
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                username TEXT UNIQUE NOT NULL,
                email TEXT UNIQUE NOT NULL,
                phone TEXT,
                password TEXT NOT NULL,
                role TEXT DEFAULT 'user',
                status TEXT DEFAULT 'active',
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                last_login DATETIME
            );

            CREATE TABLE IF NOT EXISTS inquiries (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                email TEXT NOT NULL,
                phone TEXT,
                service_package TEXT,
                location TEXT,
                message TEXT,
                status TEXT DEFAULT 'new',
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS activity_logs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER,
                action TEXT NOT NULL,
                details TEXT,
                ip_address TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS site_settings (
                key TEXT PRIMARY KEY,
                val TEXT
            );

            CREATE TABLE IF NOT EXISTS starlink_kits (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                kit_number TEXT NOT NULL,
                model TEXT DEFAULT 'Starlink Standard Gen 3 V4',
                plan_name TEXT DEFAULT 'Dedicated Business PKS Enterprise',
                location TEXT DEFAULT 'Terminal Operasional',
                status TEXT DEFAULT 'online',
                ip_address TEXT DEFAULT '100.64.12.81',
                sla_percent REAL DEFAULT 99.98,
                download_speed INTEGER DEFAULT 285,
                upload_speed INTEGER DEFAULT 45,
                ping_ms INTEGER DEFAULT 24,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );
        ");
    } else {
        // MySQL
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS users (
                id INT AUTO_INCREMENT PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                username VARCHAR(50) UNIQUE NOT NULL,
                email VARCHAR(100) UNIQUE NOT NULL,
                phone VARCHAR(30),
                password VARCHAR(255) NOT NULL,
                role VARCHAR(20) DEFAULT 'user',
                status VARCHAR(20) DEFAULT 'active',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                last_login TIMESTAMP NULL
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

            CREATE TABLE IF NOT EXISTS inquiries (
                id INT AUTO_INCREMENT PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                email VARCHAR(100) NOT NULL,
                phone VARCHAR(30),
                service_package VARCHAR(100),
                location VARCHAR(150),
                message TEXT,
                status VARCHAR(20) DEFAULT 'new',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

            CREATE TABLE IF NOT EXISTS activity_logs (
                id INT AUTO_INCREMENT PRIMARY KEY,
                user_id INT,
                action VARCHAR(100) NOT NULL,
                details TEXT,
                ip_address VARCHAR(45),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

            CREATE TABLE IF NOT EXISTS site_settings (
                `key` VARCHAR(50) PRIMARY KEY,
                `val` TEXT
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

            CREATE TABLE IF NOT EXISTS starlink_kits (
                id INT AUTO_INCREMENT PRIMARY KEY,
                user_id INT NOT NULL,
                kit_number VARCHAR(30) NOT NULL,
                model VARCHAR(100) DEFAULT 'Starlink Standard Gen 3 V4',
                plan_name VARCHAR(100) DEFAULT 'Dedicated Business PKS Enterprise',
                location VARCHAR(150) DEFAULT 'Terminal Operasional',
                status VARCHAR(20) DEFAULT 'online',
                ip_address VARCHAR(50) DEFAULT '100.64.12.81',
                sla_percent DECIMAL(5,2) DEFAULT 99.98,
                download_speed INT DEFAULT 285,
                upload_speed INT DEFAULT 45,
                ping_ms INT DEFAULT 24,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
        ");
    }

    // Seed default admin if table is empty
    $stmt = $pdo->query("SELECT COUNT(*) as count FROM users");
    $rowCount = $stmt->fetchColumn();

    if ($rowCount == 0) {
        $adminPassword = password_hash('admin123', PASSWORD_BCRYPT);
        $insert = $pdo->prepare("
            INSERT INTO users (name, username, email, phone, password, role, status, created_at)
            VALUES (:name, :username, :email, :phone, :password, :role, 'active', datetime('now'))
        ");
        
        // Handle SQLite vs MySQL datetime syntax
        if ($driver !== 'sqlite') {
            $insert = $pdo->prepare("
                INSERT INTO users (name, username, email, phone, password, role, status, created_at)
                VALUES (:name, :username, :email, :phone, :password, :role, 'active', NOW())
            ");
        }

        $insert->execute([
            ':name'     => 'Administrator Data Lake',
            ':username' => 'admin',
            ':email'    => 'admin@datalake.id',
            ':phone'    => '08170117800',
            ':password' => $adminPassword,
            ':role'     => 'admin'
        ]);

        // Seed initial sample inquiries for the dashboard to demonstrate rich management
        $seedInquiry = $pdo->prepare("
            INSERT INTO inquiries (name, email, phone, service_package, location, message, status)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        ");
        $seedInquiry->execute([
            'Budi Pratama',
            'budi@pratamatech.co.id',
            '081298765432',
            'Starlink Standard (Residensial)',
            'Jakarta Selatan',
            'Mohon penawaran harga paket pemasangan di daerah Kemang.',
            'new'
        ]);
        $seedInquiry->execute([
            'Siti Rahmawati',
            'siti.r@borneologistics.com',
            '081387654321',
            'Starlink Mini (Jelajah)',
            'Balikpapan, Kalimantan Timur',
            'Tertarik untuk armada lapangan kami di area terpencil Kalimantan.',
            'contacted'
        ]);
    }

    // Ensure Dedicated PKS Client User 'snet12' (PT NETWORK INOVATIF SOLUTIONS) exists
    try {
        $checkUser = $pdo->prepare("SELECT id FROM users WHERE username = ?");
        $checkUser->execute(['snet12']);
        $snetUser = $checkUser->fetch();
        if (!$snetUser) {
            $snetPass = password_hash('Musawir1312', PASSWORD_BCRYPT);
            $timeCol = ($driver === 'sqlite') ? "datetime('now')" : "NOW()";
            $insSnet = $pdo->prepare("
                INSERT INTO users (name, username, email, phone, password, role, status, created_at)
                VALUES (?, ?, ?, ?, ?, 'user', 'active', $timeCol)
            ");
            $insSnet->execute([
                'PT NETWORK INOVATIF SOLUTIONS',
                'snet12',
                'admin@snetwifi.com',
                '082321451749',
                $snetPass
            ]);
            $snet_id = (int)$pdo->lastInsertId();
            get_user_starlink_kits($snet_id);
        }
    } catch (Exception $e) {
        // Continue
    }
}

/**
 * Site Settings & Contact Helpers
 */
function get_site_setting($key, $default = '') {
    try {
        $pdo = get_db_connection();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);
        $col = ($driver === 'sqlite') ? "key" : "`key`";
        $stmt = $pdo->prepare("SELECT val FROM site_settings WHERE $col = ? LIMIT 1");
        $stmt->execute([$key]);
        $val = $stmt->fetchColumn();
        return ($val !== false && $val !== null && $val !== '') ? $val : $default;
    } catch (Exception $e) {
        return $default;
    }
}

function set_site_setting($key, $value) {
    try {
        $pdo = get_db_connection();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);
        if ($driver === 'sqlite') {
            $stmt = $pdo->prepare("INSERT INTO site_settings (key, val) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET val = excluded.val");
        } else {
            $stmt = $pdo->prepare("INSERT INTO site_settings (`key`, `val`) VALUES (?, ?) ON DUPLICATE KEY UPDATE `val` = VALUES(`val`)");
        }
        return $stmt->execute([$key, $value]);
    } catch (Exception $e) {
        return false;
    }
}

function get_wa_number() {
    if (defined('WA_PHONE') && WA_PHONE !== '') {
        return WA_PHONE;
    }
    return get_site_setting('wa_number', '08170117800');
}

function get_wa_url($message = '') {
    $phone = preg_replace('/[^0-9]/', '', get_wa_number());
    if (substr($phone, 0, 1) === '0') {
        $phone = '62' . substr($phone, 1);
    } elseif (substr($phone, 0, 2) !== '62') {
        $phone = '62' . $phone;
    }
    return "https://api.whatsapp.com/send?phone=" . $phone . ($message !== '' ? "&text=" . urlencode($message) : '');
}

/**
 * Generate random Starlink Kit Number: KIT******** (KIT followed by 8 characters)
 */
function generate_starlink_kit_number() {
    $chars = '0123456789ABCDEFGHJKLMNPQRSTUVWXYZ';
    $code = 'KIT';
    for ($i = 0; $i < 8; $i++) {
        $code .= $chars[random_int(0, strlen($chars) - 1)];
    }
    return $code;
}

/**
 * Get or initialize 3 Starlink Gen 3 V4 kits for a Dedicated PKS user
 */
function get_user_starlink_kits($user_id) {
    $pdo = get_db_connection();
    $stmt = $pdo->prepare("SELECT * FROM starlink_kits WHERE user_id = ? ORDER BY id ASC");
    $stmt->execute([$user_id]);
    $kits = $stmt->fetchAll();

    if (empty($kits)) {
        $locations = [
            'Terminal A',
            'Terminal B',
            'Terminal C'
        ];
        $telemetries = [
            ['down' => 284, 'up' => 48, 'ping' => 22, 'ip' => '100.64.18.24', 'sla' => 99.98],
            ['down' => 218, 'up' => 38, 'ping' => 28, 'ip' => '100.64.18.25', 'sla' => 99.95],
            ['down' => 265, 'up' => 42, 'ping' => 24, 'ip' => '100.64.18.26', 'sla' => 99.99],
        ];

        for ($i = 0; $i < 3; $i++) {
            $kit_no = generate_starlink_kit_number();
            $ins = $pdo->prepare("
                INSERT INTO starlink_kits (user_id, kit_number, model, plan_name, location, status, ip_address, sla_percent, download_speed, upload_speed, ping_ms)
                VALUES (?, ?, 'Starlink Standard Gen 3 (V4)', 'Dedicated Business PKS Enterprise', ?, 'online', ?, ?, ?, ?, ?)
            ");
            $ins->execute([
                $user_id,
                $kit_no,
                $locations[$i],
                $telemetries[$i]['ip'],
                $telemetries[$i]['sla'],
                $telemetries[$i]['down'],
                $telemetries[$i]['up'],
                $telemetries[$i]['ping'],
            ]);
        }

        $stmt = $pdo->prepare("SELECT * FROM starlink_kits WHERE user_id = ? ORDER BY id ASC");
        $stmt->execute([$user_id]);
        $kits = $stmt->fetchAll();
    }

    return $kits;
}

/**
 * Dedicated PKS Subscription Billing History (9 Jt/month, Feb 2025 to Present, All Lunas)
 */
function get_pks_billing_history() {
    $months = [
        ['period' => 'Oktober 2026', 'code' => '2026-10', 'paid_date' => '05 Okt 2026', 'inv' => 'INV/DLI/202610/0842'],
        ['period' => 'September 2026', 'code' => '2026-09', 'paid_date' => '05 Sep 2026', 'inv' => 'INV/DLI/202609/0831'],
        ['period' => 'Agustus 2026', 'code' => '2026-08', 'paid_date' => '05 Agu 2026', 'inv' => 'INV/DLI/202608/0820'],
        ['period' => 'Juli 2026', 'code' => '2026-07', 'paid_date' => '05 Jul 2026', 'inv' => 'INV/DLI/202607/0809'],
        ['period' => 'Juni 2026', 'code' => '2026-06', 'paid_date' => '05 Jun 2026', 'inv' => 'INV/DLI/202606/0798'],
        ['period' => 'Mei 2026', 'code' => '2026-05', 'paid_date' => '05 Mei 2026', 'inv' => 'INV/DLI/202605/0787'],
        ['period' => 'April 2026', 'code' => '2026-04', 'paid_date' => '05 Apr 2026', 'inv' => 'INV/DLI/202604/0776'],
        ['period' => 'Maret 2026', 'code' => '2026-03', 'paid_date' => '05 Mar 2026', 'inv' => 'INV/DLI/202603/0765'],
        ['period' => 'Februari 2026', 'code' => '2026-02', 'paid_date' => '05 Feb 2026', 'inv' => 'INV/DLI/202602/0754'],
        ['period' => 'Januari 2026', 'code' => '2026-01', 'paid_date' => '05 Jan 2026', 'inv' => 'INV/DLI/202601/0743'],
        ['period' => 'Desember 2025', 'code' => '2025-12', 'paid_date' => '05 Des 2025', 'inv' => 'INV/DLI/202512/0732'],
        ['period' => 'November 2025', 'code' => '2025-11', 'paid_date' => '05 Nov 2025', 'inv' => 'INV/DLI/202511/0721'],
        ['period' => 'Oktober 2025', 'code' => '2025-10', 'paid_date' => '05 Okt 2025', 'inv' => 'INV/DLI/202510/0710'],
        ['period' => 'September 2025', 'code' => '2025-09', 'paid_date' => '05 Sep 2025', 'inv' => 'INV/DLI/202509/0699'],
        ['period' => 'Agustus 2025', 'code' => '2025-08', 'paid_date' => '05 Agu 2025', 'inv' => 'INV/DLI/202508/0688'],
        ['period' => 'Juli 2025', 'code' => '2025-07', 'paid_date' => '05 Jul 2025', 'inv' => 'INV/DLI/202507/0677'],
        ['period' => 'Juni 2025', 'code' => '2025-06', 'paid_date' => '05 Jun 2025', 'inv' => 'INV/DLI/202506/0666'],
        ['period' => 'Mei 2025', 'code' => '2025-05', 'paid_date' => '05 Mei 2025', 'inv' => 'INV/DLI/202505/0655'],
        ['period' => 'April 2025', 'code' => '2025-04', 'paid_date' => '05 Apr 2025', 'inv' => 'INV/DLI/202504/0644'],
        ['period' => 'Maret 2025', 'code' => '2025-03', 'paid_date' => '05 Mar 2025', 'inv' => 'INV/DLI/202503/0633'],
        ['period' => 'Februari 2025', 'code' => '2025-02', 'paid_date' => '05 Feb 2025', 'inv' => 'INV/DLI/202502/0622'],
    ];

    $result = [];
    foreach ($months as $m) {
        $result[] = [
            'invoice_no' => $m['inv'],
            'period' => $m['period'],
            'description' => 'Dedicated Bandwidth Priority PKS (3x Starlink Gen 3 V4)',
            'amount' => 9000000,
            'amount_formatted' => 'Rp 9.000.000',
            'status' => 'LUNAS',
            'paid_date' => $m['paid_date'],
            'payment_method' => 'Bank Mandiri Corporate Auto-Debit',
            'pks_number' => 'PKS-DLI/STARLINK-DEDICATED/2025-0082'
        ];
    }
    return $result;
}

