<?php
/**
 * Database Connection & Migration Handler
 * Supports both SQLite (Zero-config ready) and MySQL
 * PT Data Lake Indonesia Web Portal
 */

// Load custom configuration if generated by installer
if (file_exists(__DIR__ . '/config.php')) {
    require_once __DIR__ . '/config.php';
}

// Default Configuration Fallbacks
if (!defined('DB_TYPE')) define('DB_TYPE', 'sqlite'); // 'sqlite' or 'mysql'
if (!defined('DB_HOST')) define('DB_HOST', '127.0.0.1');
if (!defined('DB_PORT')) define('DB_PORT', '3306');
if (!defined('DB_NAME')) define('DB_NAME', 'datalake_db');
if (!defined('DB_USER')) define('DB_USER', 'root');
if (!defined('DB_PASS')) define('DB_PASS', '');

function get_db_connection() {
    static $pdo = null;

    if ($pdo !== null) {
        return $pdo;
    }

    try {
        if (DB_TYPE === 'sqlite') {
            $db_dir = __DIR__ . '/../database';
            if (!is_dir($db_dir)) {
                mkdir($db_dir, 0755, true);
            }
            $db_path = $db_dir . '/datalake.sqlite';
            $pdo = new PDO("sqlite:" . $db_path);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
            $pdo->exec("PRAGMA foreign_keys = ON;");
        } else {
            $dsn = "mysql:host=" . DB_HOST . ";port=" . DB_PORT . ";dbname=" . DB_NAME . ";charset=utf8mb4";
            $pdo = new PDO($dsn, DB_USER, DB_PASS, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ]);
        }

        // Initialize tables if needed
        init_db_tables($pdo);

    } catch (PDOException $e) {
        // Fallback to SQLite if MySQL fails and was selected
        if (DB_TYPE === 'mysql') {
            try {
                $db_dir = __DIR__ . '/../database';
                if (!is_dir($db_dir)) {
                    mkdir($db_dir, 0755, true);
                }
                $db_path = $db_dir . '/datalake.sqlite';
                $pdo = new PDO("sqlite:" . $db_path);
                $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
                $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
                $pdo->exec("PRAGMA foreign_keys = ON;");
                init_db_tables($pdo);
                return $pdo;
            } catch (Exception $fallback_e) {
                die("Database Error (MySQL failed, SQLite fallback failed): " . htmlspecialchars($fallback_e->getMessage()));
            }
        }
        die("Database Connection Error: " . htmlspecialchars($e->getMessage()));
    }

    return $pdo;
}

function init_db_tables(PDO $pdo) {
    $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

    if ($driver === 'sqlite') {
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                username TEXT UNIQUE NOT NULL,
                email TEXT UNIQUE NOT NULL,
                phone TEXT,
                password TEXT NOT NULL,
                role TEXT DEFAULT 'user',
                status TEXT DEFAULT 'active',
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                last_login DATETIME
            );

            CREATE TABLE IF NOT EXISTS inquiries (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                email TEXT NOT NULL,
                phone TEXT,
                service_package TEXT,
                location TEXT,
                message TEXT,
                status TEXT DEFAULT 'new',
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS activity_logs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER,
                action TEXT NOT NULL,
                details TEXT,
                ip_address TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS site_settings (
                key TEXT PRIMARY KEY,
                val TEXT
            );
        ");
    } else {
        // MySQL
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS users (
                id INT AUTO_INCREMENT PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                username VARCHAR(50) UNIQUE NOT NULL,
                email VARCHAR(100) UNIQUE NOT NULL,
                phone VARCHAR(30),
                password VARCHAR(255) NOT NULL,
                role VARCHAR(20) DEFAULT 'user',
                status VARCHAR(20) DEFAULT 'active',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                last_login TIMESTAMP NULL
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

            CREATE TABLE IF NOT EXISTS inquiries (
                id INT AUTO_INCREMENT PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                email VARCHAR(100) NOT NULL,
                phone VARCHAR(30),
                service_package VARCHAR(100),
                location VARCHAR(150),
                message TEXT,
                status VARCHAR(20) DEFAULT 'new',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

            CREATE TABLE IF NOT EXISTS activity_logs (
                id INT AUTO_INCREMENT PRIMARY KEY,
                user_id INT,
                action VARCHAR(100) NOT NULL,
                details TEXT,
                ip_address VARCHAR(45),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

            CREATE TABLE IF NOT EXISTS site_settings (
                `key` VARCHAR(50) PRIMARY KEY,
                `val` TEXT
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
        ");
    }

    // Seed default admin if table is empty
    $stmt = $pdo->query("SELECT COUNT(*) as count FROM users");
    $rowCount = $stmt->fetchColumn();

    if ($rowCount == 0) {
        $adminPassword = password_hash('admin123', PASSWORD_BCRYPT);
        $insert = $pdo->prepare("
            INSERT INTO users (name, username, email, phone, password, role, status, created_at)
            VALUES (:name, :username, :email, :phone, :password, :role, 'active', datetime('now'))
        ");
        
        // Handle SQLite vs MySQL datetime syntax
        if ($driver !== 'sqlite') {
            $insert = $pdo->prepare("
                INSERT INTO users (name, username, email, phone, password, role, status, created_at)
                VALUES (:name, :username, :email, :phone, :password, :role, 'active', NOW())
            ");
        }

        $insert->execute([
            ':name'     => 'Administrator Data Lake',
            ':username' => 'admin',
            ':email'    => 'admin@datalake.id',
            ':phone'    => '08170117800',
            ':password' => $adminPassword,
            ':role'     => 'admin'
        ]);

        // Seed initial sample inquiries for the dashboard to demonstrate rich management
        $seedInquiry = $pdo->prepare("
            INSERT INTO inquiries (name, email, phone, service_package, location, message, status)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        ");
        $seedInquiry->execute([
            'Budi Pratama',
            'budi@pratamatech.co.id',
            '081298765432',
            'Starlink Standard (Residensial)',
            'Jakarta Selatan',
            'Mohon penawaran harga paket pemasangan di daerah Kemang.',
            'new'
        ]);
        $seedInquiry->execute([
            'Siti Rahmawati',
            'siti.r@borneologistics.com',
            '081387654321',
            'Starlink Mini (Jelajah)',
            'Balikpapan, Kalimantan Timur',
            'Tertarik untuk armada lapangan kami di area terpencil Kalimantan.',
            'contacted'
        ]);
    }
}
